# Generated by Django 5.1.4 on 2024-12-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('asosiy', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Yonalish',
                'verbose_name_plural': 'Yonalishlar',
            },
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('jins', models.CharField(choices=[('m', 'Erkak'), ('f', 'Ayol')], max_length=5)),
                ('daraja', models.CharField(choices=[('b', 'Bakalavr'), ('m', 'Magistr')], max_length=15)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fan')),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': 'Ustozlar',
            },
        ),
        migrations.AddField(
            model_name='fan',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yonalish'),
        ),
    ]
